#include "StateGame.hpp"


#define DEMO_TITLE_WIDTH	(SCREEN_WIDTH - 2 * SPACE)
#define DEMO_TITLE_HEIGHT	(OFFSET_MAZE_Y - 2 * SPACE) 
#define DEMO_OFFSET_TITLE_X		(SPACE + DEMO_TITLE_WIDTH / 2) 
#define DEMO_OFFSET_TITLE_Y		(SPACE + DEMO_TITLE_HEIGHT / 2)

#define DEMO_NUMBER_OF_BOXES 5
#define DEMO_NUMBER_OF_BUTTONS 4

#define DEMO_INFO_HEIGHT (SCREEN_MAZE_Y / DEMO_NUMBER_OF_BOXES)
#define DEMO_INFO_WIDTH (SCREEN_WIDTH - SCREEN_MAZE_X - 2 * SPACE)

#define DEMO_OFFSET_ALGO_X (OFFSET_MAZE_X + SCREEN_MAZE_X + 5 + DEMO_INFO_WIDTH / 2)
#define DEMO_OFFSET_ALGO_Y (OFFSET_MAZE_Y + DEMO_INFO_HEIGHT / 4)
#define DEMO_OFFSET_ALGO_NAME_X DEMO_OFFSET_ALGO_X
#define DEMO_OFFSET_ALGO_NAME_Y (DEMO_OFFSET_ALGO_Y + DEMO_INFO_HEIGHT / 2)

#define DEMO_BUTTON_HEIGHT (DEMO_INFO_HEIGHT / 2)
#define DEMO_BUTTON_WIDTH (DEMO_INFO_WIDTH / 3 * 2)

#define	DEMO_OFFSET_CHOOSE_ALGO_X DEMO_OFFSET_ALGO_X
#define DEMO_OFFSET_CHOOSE_ALGO_Y (DEMO_OFFSET_ALGO_NAME_Y + DEMO_INFO_HEIGHT / 4 * 3)

#define DEMO_OFFSET_FIND_X DEMO_OFFSET_ALGO_X
#define DEMO_OFFSET_FIND_Y (DEMO_OFFSET_CHOOSE_ALGO_Y + DEMO_INFO_HEIGHT)

#define DEMO_OFFSET_GENERATE_X DEMO_OFFSET_FIND_X
#define DEMO_OFFSET_GENERATE_Y (DEMO_OFFSET_FIND_Y + DEMO_INFO_HEIGHT)

#define DEMO_OFFSET_RETURN_MENU_X DEMO_OFFSET_GENERATE_X
#define DEMO_OFFSET_RETURN_MENU_Y (DEMO_OFFSET_GENERATE_Y + DEMO_INFO_HEIGHT)
